import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowCounterClockwise, ArrowsLeftRight, BookOpenText, Brain, Ear, Gauge, Megaphone, Repeat, SpeakerLow, Textbox, UsersFour, UsersThree } from "@phosphor-icons/react";
import { esvStandardNotice, questions } from "./data/catechism.generated";
import { buildStages, hideWords } from "./session";
import { buildRecitationTimeline, clampSpeed, initialPhase, isRecitable, nextCountdownStep, revealStagger, SPEEDS, tokenizeAnswer, wordTokenIndexes } from "./recitation";
import type { RecitationRegion } from "./recitation";
import type { Question, RecitationPhase, Stage } from "./types";
import "./styles.css";

const canonical = questions as unknown as Question[];
const params = () => new URLSearchParams(location.search);
const bounded = (v: unknown, min: number, max: number, fallback: number) => { const n = Number(v); return Number.isFinite(n) ? Math.min(max, Math.max(min, Math.round(n))) : fallback; };
const savedQuestion = () => bounded(params().get("q") || localStorage.getItem("catechism-question"), 1, 62, 1);
const savedReviews = () => bounded(params().get("review") ?? localStorage.getItem("catechism-review-count"), 0, 5, 2);
const savedSpeed = () => clampSpeed(params().get("speed") ?? localStorage.getItem("catechism-speed") ?? 3);

function Window({ lit, total }: { lit: number; total: number }) { return <div className="memory-window" aria-label={`${lit} of ${total} steps complete`}>{Array.from({length: total}, (_, i) => <i key={i} className={i < lit ? "lit" : ""}/>)}</div>; }
function StageIcon({ stage }: { stage: Stage }) {
  let Icon = Ear, label = "LISTEN";
  if (stage.kind === "review") [Icon, label] = [ArrowCounterClockwise, "REVIEW"];
  else if (stage.kind.startsWith("scripture")) [Icon, label] = [BookOpenText, "SCRIPTURE"];
  else if (stage.kind === "challenge") [Icon, label] = [Brain, "FROM MEMORY"];
  else if (stage.kind === "say") {
    const modes = { whole:[UsersThree,"TOGETHER"], sides:[ArrowsLeftRight,"LEFT / RIGHT"], echo:[Repeat,"ECHO"], whisper:[SpeakerLow,"WHISPER"], backwall:[Megaphone,"STRONG VOICE"], fade:[Textbox,"MISSING WORDS"], ages:[UsersFour,"YOUNGER / OLDER"], slow:[Gauge,"SLOW THEN CLEAR"] } as const;
    [Icon, label] = modes[stage.variation!.id as keyof typeof modes];
  }
  return <div className="mode-marker" role="img" aria-labelledby="current-mode-label" data-mode-icon={stage.variation?.id ?? stage.kind} data-mode-entry="active"><Icon className="mode-icon" size="1em" aria-hidden="true"/><span className="mode-label" id="current-mode-label">{label}</span></div>;
}
function GuidedAnswer({ answer, speed, active, trailing, phase, masked }: { answer:string; speed:number; active:number; trailing:number; phase:RecitationPhase; masked:boolean }) {
  const tokens = useMemo(() => tokenizeAnswer(answer, speed), [answer, speed]);
  if (masked && phase === "ready") return <div className="answer shown">{hideWords(answer, answer.length)}</div>;
  return <div className={`answer shown word-stream phase-${phase}`}><span className="sr-only">{answer}</span><span aria-hidden="true">{tokens.map((t,i) => t.word ? <span key={i} className={`word ${i === active ? "active" : i === trailing ? "trailing" : ""}`}>{t.text}</span> : t.text)}</span></div>;
}
function GuidedQuestion({ question, speed, active, trailing }: { question:string; speed:number; active:number; trailing:number }) {
  const tokens = useMemo(() => tokenizeAnswer(question, speed), [question, speed]);
  return <h1 className="question-stream"><span className="sr-only">{question}</span><span aria-hidden="true">{tokens.map((t,i) => t.word ? <span key={i} className={`word ${i===active?"active":i===trailing?"trailing":""}`}>{t.text}</span> : t.text)}</span></h1>;
}
function RevealingAnswer({ answer, visible }: { answer:string; visible:number }) {
  const tokens=useMemo(()=>tokenizeAnswer(answer),[answer]);let word=-1;
  return <div className="answer shown reveal-stream"><span className="sr-only">{answer}</span><span aria-hidden="true">{tokens.map((token,index)=>{if(!token.word)return token.text;word++;return <span key={index} className={`reveal-word ${word<visible?"revealed":""}`}>{token.text}</span>;})}</span></div>;
}

export default function App() {
  const [selected,setSelected]=useState(savedQuestion), [reviewCount,setReviewCount]=useState(savedReviews), [speed,setSpeed]=useState(savedSpeed);
  const [running,setRunning]=useState(false), [index,setIndex]=useState(0), [phase,setPhase]=useState<RecitationPhase>("hidden"), [countdown,setCountdown]=useState("3"), [revealCount,setRevealCount]=useState(0), [activeToken,setActiveToken]=useState(-1), [activeRegion,setActiveRegion]=useState<RecitationRegion|"boundary"|null>(null), [trailingToken,setTrailingToken]=useState(-1), [trailingRegion,setTrailingRegion]=useState<RecitationRegion|null>(null), [direction,setDirection]=useState<"forward"|"back">("forward"), [about,setAbout]=useState(false);
  const timer=useRef<number | undefined>(undefined), trailTimer=useRef<number | undefined>(undefined), generation=useRef(0), deadline=useRef(0), remaining=useRef(0), countdownStep=useRef(0), wordStep=useRef(0), resumeKind=useRef<"countdown"|"word">("word"), locked=useRef(false), lastAction=useRef(0), activeTokenRef=useRef(-1), activeRegionRef=useRef<RecitationRegion|"boundary"|null>(null), runWordRef=useRef<(p:number)=>void>(()=>{}), runCountdownRef=useRef<(p:number)=>void>(()=>{}), runRevealRef=useRef<(p:number)=>void>(()=>{});
  const stages=useMemo(()=>buildStages(selected,canonical,reviewCount),[selected,reviewCount]), stage=stages[index], q=stage.question, recitable=isRecitable(stage);
  const timeline=buildRecitationTimeline(q?.question??"",q?.answer??"",speed);
  const scale=params().get("timing") === "test" ? .03 : 1;
  const clearTimer=useCallback(()=>{ generation.current++; if(timer.current!==undefined) clearTimeout(timer.current); timer.current=undefined; },[]);
  const clearTrail=useCallback(()=>{if(trailTimer.current!==undefined)clearTimeout(trailTimer.current);trailTimer.current=undefined;setTrailingToken(-1);setTrailingRegion(null);},[]);
  const clearHighlight=useCallback(()=>{clearTrail();activeTokenRef.current=-1;activeRegionRef.current=null;setActiveToken(-1);setActiveRegion(null);},[clearTrail]);
  const schedule=useCallback((delay:number,cb:()=>void)=>{ const guard=generation.current, actual=Math.max(1,delay*scale); remaining.current=actual; deadline.current=performance.now()+actual; timer.current=window.setTimeout(()=>{if(generation.current===guard)cb();},actual); },[scale]);
  const finishReveal=useCallback(()=>{clearTimer();setRevealCount(wordTokenIndexes(tokenizeAnswer(q?.answer??"")).length);setPhase("ready");},[clearTimer,q?.answer]);
  const runReveal=useCallback((position:number)=>{const total=wordTokenIndexes(tokenizeAnswer(q?.answer??"")).length;if(position>=total){schedule(200,()=>setPhase("ready"));return;}setRevealCount(position+1);schedule(revealStagger(q?.answer??""),()=>runRevealRef.current(position+1));},[q?.answer,schedule]);
  const finishWords=useCallback(()=>schedule(650,()=>{clearHighlight();setPhase("complete");}),[clearHighlight,schedule]);
  const runWord=useCallback((pos:number)=>{resumeKind.current="word";wordStep.current=pos;if(pos>=timeline.length){finishWords();return;}const step=timeline[pos];if(step.kind==="boundary"){clearHighlight();activeRegionRef.current="boundary";setActiveRegion("boundary");schedule(step.delay,()=>runWordRef.current(pos+1));return;}clearTrail();if(activeRegionRef.current==="question"||activeRegionRef.current==="answer"){setTrailingRegion(activeRegionRef.current);setTrailingToken(activeTokenRef.current);trailTimer.current=window.setTimeout(()=>{setTrailingToken(-1);setTrailingRegion(null);trailTimer.current=undefined;},160);}activeRegionRef.current=step.region;activeTokenRef.current=step.tokenIndex;setActiveRegion(step.region);setActiveToken(step.tokenIndex);schedule(step.delay,()=>runWordRef.current(pos+1));},[clearHighlight,clearTrail,finishWords,schedule,timeline]);
  const continueCountdown=useCallback((step:number)=>{const next=nextCountdownStep(step);if(next==="recite"){setPhase("reciting");runWordRef.current(0);}else runCountdownRef.current(next);},[]);
  const runCountdown=useCallback((step:number)=>{const labels=["3","2","1","Together"];resumeKind.current="countdown";countdownStep.current=step;setCountdown(labels[step]);schedule(step===3?700:800,()=>continueCountdown(step));},[continueCountdown,schedule]);
  useEffect(()=>{runWordRef.current=runWord;runCountdownRef.current=runCountdown;runRevealRef.current=runReveal;},[runCountdown,runReveal,runWord]);
  const resetCurrent=useCallback(()=>{clearTimer();clearHighlight();setRevealCount(0);setCountdown("3");setPhase(stage.kind==="challenge"?"hidden":"ready");},[clearHighlight,clearTimer,stage.kind]);
  const move=useCallback((next:number,dir:"forward"|"back")=>{if(locked.current)return;clearTimer();clearHighlight();setRevealCount(0);locked.current=true;setDirection(dir);setIndex(next);setPhase(initialPhase(stages[next]));window.setTimeout(()=>{locked.current=false;},320);},[clearHighlight,clearTimer,stages]);
  const advance=useCallback(()=>{
    const now=performance.now();if(locked.current||now-lastAction.current<180)return;lastAction.current=now;
    if(phase==="revealing"){finishReveal();return;}
    if(stage.kind==="meet"){if(phase==="hidden"){setRevealCount(0);if(matchMedia("(prefers-reduced-motion: reduce)").matches)finishReveal();else{setPhase("revealing");runReveal(0);}}else move(index<stages.length-1?index+1:0,"forward");return;}
    if(!recitable){move(index<stages.length-1?index+1:0,"forward");return;}
    if(phase==="hidden"){if(stage.kind==="challenge"){setRevealCount(0);if(matchMedia("(prefers-reduced-motion: reduce)").matches)finishReveal();else{setPhase("revealing");runReveal(0);}}else setPhase("ready");return;}
    if(phase==="ready"){clearTimer();setPhase("countdown");runCountdown(0);return;}
    if(phase==="countdown"||phase==="reciting"){remaining.current=Math.max(1,deadline.current-performance.now());resumeKind.current=phase==="countdown"?"countdown":"word";clearTimer();clearTrail();setPhase("paused");return;}
    if(phase==="paused"){setPhase(resumeKind.current==="countdown"?"countdown":"reciting");schedule(remaining.current,resumeKind.current==="countdown"?()=>continueCountdown(countdownStep.current):()=>runWord(wordStep.current+1));return;}
    if(phase==="complete")move(index<stages.length-1?index+1:0,"forward");
  },[clearTimer,clearTrail,continueCountdown,finishReveal,index,move,phase,recitable,runCountdown,runReveal,runWord,schedule,stage.kind,stages.length]);
  const back=useCallback(()=>{if(phase==="revealing"){clearTimer();setRevealCount(0);setPhase("hidden");return;}if(recitable&&["countdown","reciting","paused","complete"].includes(phase)){resetCurrent();return;}if(index>0)move(index-1,"back");},[clearTimer,index,move,phase,recitable,resetCurrent]);
  const stop=useCallback(()=>{clearTimer();clearHighlight();setRevealCount(0);locked.current=false;lastAction.current=0;setCountdown("3");setPhase("hidden");setRunning(false);},[clearHighlight,clearTimer]);
  const restart=useCallback(()=>{clearTimer();clearHighlight();setRevealCount(0);locked.current=false;lastAction.current=0;setIndex(0);setPhase(initialPhase(stages[0]));},[clearHighlight,clearTimer,stages]);
  const begin=()=>{clearTimer();clearHighlight();setRevealCount(0);locked.current=false;lastAction.current=0;setCountdown("3");localStorage.setItem("catechism-question",String(selected));localStorage.setItem("catechism-review-count",String(reviewCount));localStorage.setItem("catechism-speed",String(speed));const test=params().get("timing")==="test"?"&timing=test":"";history.replaceState(null,"",`?q=${selected}&review=${reviewCount}&speed=${speed}${test}`);setIndex(0);setPhase(initialPhase(stages[0]));setRunning(true);};
  useEffect(()=>()=>{clearTimer();if(trailTimer.current!==undefined)clearTimeout(trailTimer.current);},[clearTimer]);
  useEffect(()=>{const fn=()=>{if(!document.hidden)return;if(phase==="revealing"){clearTimer();setRevealCount(0);setPhase("hidden");}else if(phase==="countdown"||phase==="reciting"){remaining.current=Math.max(1,deadline.current-performance.now());resumeKind.current=phase==="countdown"?"countdown":"word";clearTimer();clearTrail();setPhase("paused");}};document.addEventListener("visibilitychange",fn);return()=>document.removeEventListener("visibilitychange",fn);},[clearTimer,clearTrail,phase]);
  useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(!running)return;const forward=e.key===" "||e.key==="ArrowRight"||e.key==="ArrowDown"||e.key==="PageDown", backward=e.key==="ArrowLeft"||e.key==="ArrowUp"||e.key==="PageUp";if(forward){e.preventDefault();advance();}else if(backward){e.preventDefault();back();}else if(e.key==="Escape"){e.preventDefault();stop();}};addEventListener("keydown",fn);return()=>removeEventListener("keydown",fn);},[advance,back,running,stop]);

  if(about)return <main className="about"><article><p className="kicker">About · Copyright</p><h1>Catechism Time</h1><p>This app uses the full official church catechism wording. Scripture selections keep their workbook review status visible.</p><h2>ESV copyright notice</h2>{esvStandardNotice.split("\n\n").map(p=><p key={p}>{p}</p>)}<p><a href="https://www.esv.org/" target="_blank" rel="noreferrer">Read about the ESV at esv.org</a></p><button className="start" onClick={()=>setAbout(false)}>Back to setup</button></article></main>;
  if(!running)return <main className="setup"><div className="setup-shell"><div className="setup-brand"><span className="brand">Catechism Time</span><button className="text-button" onClick={()=>setAbout(true)}>About and copyright</button></div><section className="setup-inner"><p className="kicker">Set up this Sunday</p><h1>Which question are we learning?</h1><p className="setup-lead">One question for the whole room. Your clicker moves every step.</p><label htmlFor="question">Current question</label><div className="picker"><button aria-label="Previous question" onClick={()=>setSelected(n=>Math.max(1,n-1))} disabled={selected===1}>−</button><select id="question" value={selected} onChange={e=>setSelected(Number(e.target.value))} data-testid="question-select">{canonical.map(item=><option key={item.id} value={item.number}>{item.number}. {item.question}</option>)}</select><button aria-label="Next question" onClick={()=>setSelected(n=>Math.min(62,n+1))} disabled={selected===62}>+</button></div><div className="setup-options"><div className="review-control"><label htmlFor="review-count">Past questions to review</label><select id="review-count" data-testid="review-count" value={reviewCount} onChange={e=>setReviewCount(Number(e.target.value))}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n===0?"None":n}</option>)}</select></div><div className="review-control"><label htmlFor="recitation-speed">Reading pace</label><select id="recitation-speed" data-testid="recitation-speed" value={speed} onChange={e=>setSpeed(clampSpeed(e.target.value))}>{SPEEDS.map(item=><option key={item.value} value={item.value}>{item.value} · {item.label}</option>)}</select></div></div>{reviewCount>selected-1&&<p className="availability">{Math.max(0,selected-1)} available this week</p>}{canonical[selected-1].scripture.referenceReviewStatus==="Needs Human Decision"&&<p className="setup-note">Scripture selection needs review</p>}<button className="start" onClick={begin}>Start Catechism Time <span>→</span></button><footer className="setup-foot"><span>Full answers · ESV Scripture</span><span>Space / → / PgDn leads · ← / PgUp back · Esc exits</span></footer></section></div></main>;
  const presenterLed=stage.kind==="meet", showAnswer=(recitable||presenterLed)&&phase!=="hidden", displayTitle=stage.kind==="say"?q!.question:stage.title, masked=stage.kind==="say"&&stage.variation?.mode==="hidden";
  const revealMoment=presenterLed||stage.kind==="challenge", prompt=phase==="hidden"?"Reveal answer":phase==="revealing"?"Revealing answer · press Space to finish":presenterLed?"Continue to group recitation":phase==="ready"?"Start together":phase==="paused"?"Paused · press Space to continue":phase==="complete"?"Finished · press Space for next":phase==="countdown"?"Get ready":"Say it together";
  const questionActive=activeRegion==="question"?activeToken:-1, answerActive=activeRegion==="answer"?activeToken:-1, questionTrailing=trailingRegion==="question"?trailingToken:-1, answerTrailing=trailingRegion==="answer"?trailingToken:-1;
  return <main className={`session kind-${stage.kind} recitation-${phase}`} data-stage={stage.kind} data-phase={phase} data-active-region={activeRegion??"none"}><header><div className="header-actions"><button className="quiet" onClick={stop}>Exit</button><button className="quiet" onClick={restart}>Restart</button></div><Window lit={index} total={stages.length-1}/><span className="step">{index+1} / {stages.length}</span></header><section key={`${index}-${direction}`} className={`stage stage-${direction}`} onClick={advance}>{stage.kind!=="close"&&<StageIcon stage={stage}/>} {displayTitle&&(recitable&&phase!=="hidden"?<GuidedQuestion question={displayTitle} speed={speed} active={questionActive} trailing={questionTrailing}/>:<h1>{displayTitle}</h1>)}{recitable&&!revealMoment&&<div key={phase === "hidden" ? "hidden" : "answer"} className="answer-motion">{showAnswer?<GuidedAnswer answer={q!.answer} speed={speed} active={answerActive} trailing={answerTrailing} phase={phase} masked={masked}/>:<div className="answer hidden-answer" aria-label="Answer hidden"/>}</div>}{stage.kind==="challenge"&&phase!=="hidden"&&phase!=="countdown"&&phase!=="reciting"&&phase!=="paused"&&phase!=="complete"&&<RevealingAnswer answer={q!.answer} visible={revealCount}/>} {stage.kind==="challenge"&&["countdown","reciting","paused","complete"].includes(phase)&&<GuidedAnswer answer={q!.answer} speed={speed} active={answerActive} trailing={answerTrailing} phase={phase} masked={false}/>} {presenterLed&&(phase==="revealing"||phase==="ready")?<RevealingAnswer answer={q!.answer} visible={revealCount}/>:presenterLed?<div className="answer hidden-answer" aria-label="Answer hidden"/>:null}{recitable&&phase==="countdown"&&<div className="countdown" role="status" aria-live="polite"><span key={countdown} data-countdown-beat={countdown}>{countdown}</span></div>}{recitable&&phase==="paused"&&<div className="pause-badge" role="status">Paused</div>}{stage.kind==="scripture"&&<blockquote><p>{stage.scriptureText}</p></blockquote>}{stage.kind==="scripture-pending"&&<div className="leader pending"><b>Scripture selection needs a human decision</b><p>The candidate ESV text is not shown as approved teaching content.</p><p>{q!.scripture.note}</p></div>}</section><footer className="controls"><button onClick={back} disabled={index===0&&(phase==="hidden"||phase==="ready")}>← Back</button><span>{stage.kind==="close"?"":recitable||presenterLed?prompt:"Tap anywhere or press Space"}</span><button onClick={()=>stage.kind==="close"?restart():advance()}>{stage.kind==="close"?"Again":phase==="revealing"?"Finish reveal":phase==="countdown"||phase==="reciting"?"Pause":phase==="paused"?"Continue":phase==="complete"||(!recitable&&!presenterLed)?"Next →":phase==="hidden"?"Reveal":presenterLed?"Next →":"Start"}</button></footer></main>;
}
